### ISSUE TITLE
one pager core names don't match the cd2h-archive web site names

### ISSUE THREAD

**Issue by eichmann** [data2health/admin#1]

**Comment by cgcook** [comment]
@jmcmurry @kristiholmes do either of you have the original file for the [one pager](https://drive.google.com/file/d/1zCsgcI7pGsrUQCpBgrvwFskis9t7EmlN/view)?  I'm only seeing the PDF version in drive.

**Comment by kristiholmes** [comment]
@jmcmurry has it.

**Comment by jmcmurry** [comment]
This is the source file (done in illustrator); I will update now.

**Comment by jmcmurry** [comment]
OK; I have simplified, updated, and restyled for consistency; please have a look [here](https://ctsa.ncats.nih.gov/cd2h-archive/cd2h-one-pager/?preview=true).

**Comment by cgcook** [comment]
Looks good; except I think you caught a bit of the asterisk from the Core diagram on the bottom left. 
![Screen Shot 2019-07-17 at 3 10 07 PM](https://user-images.githubusercontent.com/38416493/61415296-1d877e80-a8a5-11e9-82fc-d2b142f02ded.png)

**Comment by cgcook** [comment]
Thanks, Julie.  The Core diagram is slightly out of date; the roadmap in GitHub is accurate: https://github.com/data2health/roadmap
